### ISSUE TITLE
Configurable Reminder Intervals

### ISSUE THREAD

**Issue by jhunt** [jhunt/shout#2]
Currently, the `SCAN` function imposes a preset reminder interval of 1 minute.  Great for testing; lousy for production use.

Make this configurable, via the new `$SHOUT_INTERVAL` environment variable, which must parse as a positive integer greater than 60 (minutes).  Calculate that out into seconds for the code.

**Comment by aanelli** [comment]
James to James: let's do that by setting on a per notification handler basis

**Comment by jhunt** [comment]
To elaborate:

```
((for *
    (when *
      (suppress 24 hours)
      (slack ...))))
```

It is an error to have more than one `(suppress ...)` form in a WHEN handler.

Support units:
  - days
  - hours
  - minutes
