### ISSUE TITLE
Add authentication to API

### ISSUE THREAD

**Issue by dennisjbell** [jhunt/shout#7]
No one should just be able to publish updates to the Shout! API endpoint which would be propagated through to the various endpoint as if they were official.  We need some form of authentication in front of the API called: HTTP Basic Authentication should do fine.

**Comment by dennisjbell** [comment]
The only reason we might want to go beyond Basic Auth is if we want to support roles, such as to differentiate who can push alerts and who can view/push rules.  I suppose this can be facilitated with two different basic auth values.

**Comment by jhunt** [comment]
Done!
