### ISSUE TITLE
Support metadata in rules

### ISSUE THREAD

**Issue by dennisjbell** [jhunt/shout#9]
When accepting posts for "shouting", there are minimal reserved words that are used to specify the customized content of the post: topic, ok, link and message.  For other aspects of the message, the rules hierarchy are used to assemble the message per plugin based on those reserved words.

However, there are circumstances that need to be able to pass other customized metadata in the post body that can be used by the rules that can be used to produce custom behaviour (ie fields or buttons in slack, respond-to in email.

**Comment by dennisjbell** [comment]
I think this can be done simply by adding more key-value pairs in the post body.  The question is should the rules state what keys are required or optional and error on missing or extra?

**Comment by jhunt** [comment]
WIP on branch `metadata`
